baseurl = "https://tehng.onrender.com"
languageCode = "en-us"
theme = "hugo-theme-cleanwhite"
title = "佇遮"
[[menu.main]]
identifier = "blog"
name = "blog"
url = "blogs/"
weight = 3
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"
weight = 2
[params]
header_image = "img/home-bg-jeep.jpg"
