baseurl = "https://tehng.onrender.com"
title = "佇遮"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"

[params]
  header_image = "img/home-bg-jeep.jpg"

[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"
weight = 2

[[menu.main]]
identifier = "blog"
name = "blog"
url = "blogs/"
weight = 3



